server:
  port: 8080
  servlet:
    session:
      cookie:
        same-site: none
        secure: true

spring:
  application:
    name: neosis-backend
  
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA & Hibernate Settings
  jpa:
    open-in-view: false 
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update 
    show-sql: true    
    properties:
      hibernate:
        format_sql: true

  # Google OAuth 2.0 Security Configuration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile