server:
  port: 8080
  forward-headers-strategy: framework 
  servlet:
    session:
      cookie:
        same-site: ${SESSION_COOKIE_SAME_SITE:none} 
        secure: ${SESSION_COOKIE_SECURE:false}

app:
  frontend:
    url: ${FRONTEND_URL:https://neosis-static-site.onrender.com}

spring:
  application:
    name: neosis-backend
  
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false 
    hibernate:
      ddl-auto: ${DDL_AUTO:update} 
    show-sql: ${SHOW_SQL:false}    
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile